<a href="https://colab.research.google.com/github/AarjavShahh/ML_Repo/blob/main/DMV_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1. Reshape 1D dataset of 20 soil sample IDs into a 4x5 matrix
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
z = data.reshape(4, 5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#Q2. Compute mean, median, std deviation for marks of 10 students between 50 and 100
import numpy as np

marks = np.array([90, 89, 98, 78, 87, 67, 76, 56, 65, 54])

print("Mean: ", np.mean(marks))
print("SD:  ", np.std(marks))
print("Median: ", np.median(marks))

Mean:  76.0
SD:   14.352700094407323
Median:  77.0


In [ ]:
#Q3. Time series experiment: array of size 10 with 5th element as 1 and rest 0
import numpy as np

x = np.zeros(10)
# x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Q4. Generate a 6x6 identity matrix
import numpy as np

x = np.identity(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#Q5 Square numbers dataset and slicing

import numpy as np

x = np.arange(1, 16) ** 2
x
print("First Five: ", x[:5])
print("Last Five: ", x[-3:])
print("Even Indexed: ", x[::2])

First Five:  [ 1  4  9 16 25]
Last Five:  [169 196 225]
Even Indexed:  [  1   9  25  49  81 121 169 225]


In [ ]:
#Q6 Extract main diagonal from 5x5 rainfall data
import numpy as np

rainfall_data = np.arange(1, 26)
rainfall_data = rainfall_data.reshape(5, 5)
rainfall_data


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
print("Diagonal values: ", np.diag(rainfall_data))

Diagonal values:  [ 1  7 13 19 25]


In [ ]:
#Q7 Replace negative values with 0
import numpy as np
x = np.array([1, 2, -5, 20, 19, -69, -80])
x[x < 0] = 0
x


array([ 1,  2,  0, 20, 19,  0,  0])

In [ ]:
#Q8 Weather model matrices and arithmetic operations
import numpy as np

x1 = np.random.randint(1, 11, size=(3, 3))
x1
x2 = np.random.randint(1, 11, size=(3, 3))


In [ ]:
x2

array([[ 5, 10,  3],
       [ 1,  8,  1],
       [ 4,  4, 10]])

In [ ]:
print("Sum: \n", x1 + x2)
print("Sub: \n", x1 - x2)
print("Mul: \n", x1 * x2)
print("Div: \n", x1 / x2)

Sum: 
 [[ 8 16  5]
 [ 3 10 11]
 [13  7 11]]
Sub: 
 [[-2 -4 -1]
 [ 1 -6  9]
 [ 5 -1 -9]]
Mul: 
 [[15 60  6]
 [ 2 16 10]
 [36 12 10]]
Div: 
 [[ 0.6         0.6         0.66666667]
 [ 2.          0.25       10.        ]
 [ 2.25        0.75        0.1       ]]


In [ ]:
#Q9 Survey result row-wise and column-wise totals
import numpy as np

x = np.random.randint(1, 100, size=(3, 3))
x

array([[53, 36, 22],
       [45, 56, 87],
       [12, 21, 19]])

In [ ]:
print("Row Addition: ", np.sum(x, axis=1))
print("Column Addition: ", np.sum(x, axis=0))

Row Addition:  [111 188  52]
Row Addition:  [110 113 128]


In [ ]:
#Q10 Normalize plant growth dataset between 0 and 1
import numpy as np

plant_growth = np.random.randint(1, 100, size=10)
plant_growth

array([71, 56,  4,  9, 64, 89, 21, 56, 34, 99])

In [ ]:
normalized_growth = (plant_growth - plant_growth.min()) / (plant_growth.max() - plant_growth.min())
normalized_growth

array([0.70526316, 0.54736842, 0.        , 0.05263158, 0.63157895,
       0.89473684, 0.17894737, 0.54736842, 0.31578947, 1.        ])

In [ ]:
#Q11 Dot and cross product of 3D vectors
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Dot Product: ", np.dot(x, y))
print("Cross Product: ", np.cross(x, y))

Dot Product:  32
Cross Product:  [-3  6 -3]


In [ ]:
#Q12 Simulate heights and calculate mean, variance, std dev using normal dis
import numpy as np

heights = np.random.normal(170, 10, 100)
print("Mean: ", np.mean(heights))
print("Variance: ", np.var(heights))
print("Std Dev: ", np.std(heights))

Mean:  168.9942871750643
Variance:  95.53843311645147
Std Dev:  9.774376354348725


In [ ]:
#Q13 Unique species and their frequency
import numpy as np
x = np.random.randint(1, 51, size=20)
print(x)
y, counts = np.unique(x, return_counts=True)
print("Unique Species in Array: ", y)
print("Count of the Unique Species: ", counts)


[24 14 48 16 42 35 13 30 49 31 42 19  7 26 23 28  6 27 26 16]
Unique Species in Array:  [ 6  7 13 14 16 19 23 24 26 27 28 30 31 35 42 48 49]
Count of the Unique Species:  [1 1 1 1 2 1 1 1 2 1 1 1 1 1 2 1 1]


In [ ]:
#Q14 Extract values divisible by 15
import numpy as np

x = np.random.randint(1, 100, 10)
print(x)
y = x[x % 15 == 0]
print("Numbers Divisible by 3 and 5: ", y)

[[68 65 30]
 [ 6 74 60]
 [56 34 12]]
Numbers Divisible by 3 and 5:  [30 60]


In [ ]:
#Q15 Highest, lowest, and average scores
import numpy as np

scores = np.random.randint(1, 101, size=10)
print(scores)
print("Highest Score: ", np.max(scores))
print("Lowest Score: ", np.min(scores))
print("Average Score: ", np.mean(scores))

[93 54 77 65  3 99 45 79 13 69]
Highest Score:  99
Lowest Score:  3
Average Score:  59.7


In [ ]:
# 16. Create 1-36 and reshape to 6x6, then extract 3x3 center block
import numpy as np

x = np.arange(1, 37)
x = x.reshape(6, 6)
print(x)
y = x[1:5, 1:5]
print("Center Block: \n", y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Center Block: 
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [ ]:
# 17. Stacking two arrays vertically and horizontally
import numpy as np

x = np.random.randint(1, 101, 3)
y = np.random.randint(1, 101, 3)
print("Array 1: ", x)
print("Array 2: ", y)
print("Vertical Stack: \n", np.vstack((x, y)))
print("Horizontal Stack: \n", np.hstack((x, y)))


Array 1:  [98 38 24]
Array 2:  [ 5 14  4]
Vertical Stack: 
 [[98 38 24]
 [ 5 14  4]]
Horizontal Stack: 
 [98 38 24  5 14  4]


In [ ]:
#Q18
import numpy as np

x = np.random.randint(1, 101, size=(5, 5))
x

array([[67, 69, 17, 20, 85],
       [ 5, 67, 84, 73, 64],
       [75, 10, 39, 87, 95],
       [74, 65,  8, 10, 26],
       [72, 32, 75, 99, 86]])

In [ ]:
print("Transpose: \n", np.transpose(x))

Transpose: 
 [[67  5 75 74 72]
 [69 67 10 65 32]
 [17 84 39  8 75]
 [20 73 87 10 99]
 [85 64 95 26 86]]


In [ ]:
#Q19. Image manipulation
import numpy as np

grayscale_image = np.random.randint(0, 256, size=(5, 5))
inverted_image = 255 - grayscale_image
thresholded_image = np.where(grayscale_image > 128, 255, 0)
print("Grayscale Image: \n", grayscale_image)
print("Inverted Image: \n", inverted_image)
print("Thresholded Image: \n", thresholded_image)


Grayscale Image: 
 [[ 84  46  40 156 128]
 [ 69 249 151 190 115]
 [192 142 144 217  74]
 [179  95  70 226 188]
 [187 184 234 193  82]]
Inverted Image: 
 [[171 209 215  99 127]
 [186   6 104  65 140]
 [ 63 113 111  38 181]
 [ 76 160 185  29  67]
 [ 68  71  21  62 173]]
Thresholded Image: 
 [[  0   0   0 255   0]
 [  0 255 255 255   0]
 [255 255 255 255   0]
 [255   0   0 255 255]
 [255 255 255 255   0]]


In [ ]:
# 20. Temperature data and analysis
import numpy as np

x = np.random.randint(-20, 40, size=(7, 4))
print(x)
print("Average: ", np.mean(x, axis=0))

[[ 30 -13  23  -3]
 [ 19  20  -5  26]
 [  7   3  23  33]
 [  3   0  -5  23]
 [ 32 -20  24  -6]
 [-10  35 -19  23]
 [ 34   1  12  -1]]
Average:  [16.42857143  3.71428571  7.57142857 13.57142857]


In [ ]:
y = np.max(x, axis=1)
print("Max: ", y)
y = np.max(y)
print(y)

NameError: name 'x' is not defined

In [ ]:
import numpy as np
x = np.random.randint(1, 100,)
x

5